name: wrecker-ui
version: '3.3.0.0'
synopsis: A web interface for Wrecker, the HTTP Performance Benchmarker
description: ! '''wrecker-ui'' is a web based interface to visualize performance tests
  built using the wrecker library and schedule test runs.'
category: Web
author: José Lorenzo Rodríguez
maintainer: lorenzo@seatgeek.com
license: BSD3
github: seatgeek/wrecker-ui
default-extensions:
- OverloadedStrings
ghc-options:
- -Wall
- -threaded
- -O2
- -rtsopts "-with-rtsopts=-N"
dependencies:
- base >=4 && <5
- scotty
- text
- time
- aeson
- containers
- http-types
- wai-cors
- directory
- persistent
- persistent-template
- persistent-sqlite
- persistent-postgresql
- esqueleto
- monad-control
- monad-logger
- resourcet
- transformers
- resource-pool
- postgresql-simple-url
- postgresql-simple
- process
- temporary
- bytestring
- iso8601-time
- stm
- async
- distributed-process >=0.7.3
- network-transport >=0.5.2
- network-transport-tcp
- distributed-process-simplelocalnet >=0.2.4
- distributed-process-async >=0.2.4.2
- distributed-static
- binary
- mtl
- HostAndPort
executables:
  wrecker-ui:
    main: Main.hs
    source-dirs: src
data-files:
- assets/app.js
- assets/index.html
- assets/main.css
