flags: {}
extra-package-dbs: []
packages:
- .
- location:
    git: https://github.com/lorenzo/distributed-process-async.git
    commit: cfa525120f51cdaf573a9f5df7dd819f2a816e90
  extra-dep: true
extra-deps:
- HostAndPort-0.2.0
- time-1.6.0.1
resolver: lts-10.3
